model:
  url: https://github.com/yisaienkov/this_flower_does_not_exist_demo/releases/download/v0.0.3/2021-09-12_17-37-54_conditional_wgan_generator.pt
  image_channels: 3
  z_dim: 64
  n_classes: 2

classes:
  leontodon: 0
  marigold: 1
