model:
  url: https://github.com/yisaienkov/this_flower_does_not_exist_demo/releases/download/v0.1.0/2021-09-17_10-41-51_c2wgan_64_generator.pt
  image_channels: 3
  z_dim: 64
  n_classes: 2
  image_size: 64

classes:
  leontodon: 0
  marigold: 1
