model:
  url: https://github.com/yisaienkov/this_flower_does_not_exist_demo/releases/download/v0.0.4/2021-09-13_17-03-24_c2wgan_58_generator.pt
  image_channels: 3
  z_dim: 64
  n_classes: 2
  image_size: 58

classes:
  leontodon: 0
  marigold: 1
